### ISSUE TITLE
Deployment info email received, but can't login since 'user is disabled' 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/owncloud_deployer#55] opened 2022-07-14 14:12 UTC
User trout2 received his email, but can't seem to login.

![photo_2022-07-14 16 11 31](https://user-images.githubusercontent.com/31733464/179002848-d1c6d174-70b4-4463-95af-8196a5ef92dc.jpeg)

**Comment by coesensbert** [comment] 2022-07-14 14:13
Did he also use the TF Connect login method? If so the user/password in the email should work.

https://github.com/threefoldtech/owncloud_deployer/issues/53

**Comment by sameh-farouk** [comment] 2022-07-17 16:14
Duplicate of #53

**Closed by sameh-farouk** 2022-07-17 16:14 UTC
